### ISSUE TITLE
can you add other Command?

### ISSUE THREAD

**Issue by lzctbyong** [beansoftapp/react-native-console#1]
such as :  
react-native log-android 
gradlew assembleRelease

**Comment by lzctbyong** [comment]
By the way, In the WebStorm IDE
the menu "Tool -->Reacat Native Console --> Check Reacat Native Console Update"
the Icon is too Big ...  , Fix it please
thx! nice Plugin !

**Comment by beansoftapp** [comment]
All your issues were fixed.
1. remove old big icon, now total plugin is 113.4KB big;
2. react-native log-android and gradlew assembleRelease, these functions already added and yesterday night passed IDEA's approve, so you can just update and got the function;
3. In fact WebStorm has a built-in reactive runner with debug functions enabled, you can check this:
http://m.youku.com/video/id_XMTg4NzQ2MzY3Ng==.html?spm=a2h0j.8191439.myoukuallsee.4
