### ISSUE TITLE
控制台 log-android 中文UTF-8乱码

### ISSUE THREAD

**Issue by ittianyu** [beansoftapp/react-native-console#10]

**Comment by beansoftapp** [comment]
这个问题目前比较难解决. 因为windows下终端的默认code page不是UTF8, 而IDEA的执行器底层是走到了终端的. 再我想到办法之前, 你可以手动在terminal执行CMD:

chcp 65001
adb.exe logcat *:S ReactNative:V ReactNativeJS:V

**Comment by beansoftapp** [comment]
通过查看IDEA的logcat代码, 成功解决此BUG, 请尝试新包: https://github.com/beansoftapp/react-native-console/blob/master/react-native-console.jar 亲测已OK.
