### ISSUE TITLE
How to set the current directory?

### ISSUE THREAD

**Issue by SPAHI4** [beansoftapp/react-native-console#11]
for example, I have a react-native app located in `/app`, and when I'm trying to use console:
![image](https://user-images.githubusercontent.com/1670998/29363575-3b583f1e-8299-11e7-8b1c-e000f24a7f94.png)

**Comment by beansoftapp** [comment]
I think we can use a .rnconsole file to specify where really the project file is, in that file you can specify a relative path.

**Comment by SPAHI4** [comment]
@beansoftapp is it implemented?
if not, I think it's better to save it under .idea folder

**Comment by beansoftapp** [comment]
https://github.com/beansoftapp/react-native-console/blob/master/react-native-console.jar, you can download it now , 1.0.8 will be public at IDEA plugin center soon. See github read me of how to use, so far only supports edit config file.

**Comment by beansoftapp** [comment]
And still thanks for your idea that in fact i need this function too when coding a library project with a runnable example project.
