### ISSUE TITLE
加个功能

### ISSUE THREAD

**Issue by lzctbyong** [beansoftapp/react-native-console#12]
npm start -- --reset-cache 
嘿嘿

**Comment by beansoftapp** [comment]
using a more generic way:

add scripts to your package.json:
`"scripts": { "test": "jest", "reset-cache" : "npm start -- --reset-cache" }`

click the npm dropdown toolbar button of RN Console to run it directly.
I've tested that and it works.

My log is like this:

> /usr/local/bin/npm run reset-cache

> Elm@0.0.1 reset-cache /Users/beansoft/Documents/Java/rn/AwesomeProject-subapp/rnapp
> npm start -- --reset-cache


> Elm@0.0.1 start /Users/beansoft/Documents/Java/rn/AwesomeProject-subapp/rnapp
> node node_modules/react-native/local-cli/cli.js start "--reset-cache"
