### ISSUE TITLE
File 'package.json' not found.

### ISSUE THREAD

**Issue by NunoCalvium** [beansoftapp/react-native-console#13]
It would be great if we could manually specify the npm path. My npm is not installed on the root of the project so this tool cant find the package.json.

Full error: "File 'package.json' not found. Make sure that you have run `npm install` and that you are inside a react-native project."

**Comment by beansoftapp** [comment]
Specify js project work directory, eg ./jsapp , you must create a file named .idea/.rnconsole, which content should like this:
{
  currentPath: './jsapp'
}

after that all npm commands will use this as working dir, please give a try.

**Comment by NunoCalvium** [comment]
That worked. Thanks for the quick reply. 
I think you should do some styling on your README.
