### ISSUE TITLE
快捷键

### ISSUE THREAD

**Issue by ruidalin** [beansoftapp/react-native-console#14]
希望可以添加和自定义快捷键 , 每次改完代码 ctrl+s , 然后一个reload的快捷键就能看到效果了多方便

**Comment by beansoftapp** [comment]
这个RN里面是自带自动reload的功能的. 在设备上摇晃, 打开 Enable Live Reload和Enable Hot Reloading两个菜单就可以实现修改后Ctrl+S, App立即重新加载.

**Comment by ruidalin** [comment]
但是有时候不会自动更新 , 希望还是有个快捷键可以手动更新 , 本来你的工具也有reload的按钮, 只是没有快捷键而已

**Comment by beansoftapp** [comment]
这个我调研一下看看.

**Comment by beansoftapp** [comment]
I've upload a new version for testing: https://github.com/beansoftapp/react-native-console/blob/master/react-native-console.jar , please install it and do a test. shortcut is: ctrl F2

**Comment by ruidalin** [comment]
很感谢你的跟进 ,  Thanks!!!

**Comment by beansoftapp** [comment]
new version includes this feature submitted to plugin-in central, so close this issue
