### ISSUE TITLE
Can not find environment variables 

### ISSUE THREAD

**Issue by alanpduque** [beansoftapp/react-native-console#17]
When I click on the "Debug Android" button, the console gives an error saying "SDK location not found", but when I run "react-native run-android" via command line it works perfectly.
Seems like the plugin is not able to find the ANDROID_HOME environment variable set on my OS(elementary OS 0.4.1 Loki). 

![image](https://user-images.githubusercontent.com/19227667/32903030-1ab7783a-cadb-11e7-9cbb-02176d9038c1.png)

**Comment by beansoftapp** [comment]
Seems your OS is really new. And please try this solution, add a android local config file:
yourapp/android/local.properties
sdk.dir=/Users/xxxx/Documents/Java/android-sdk-macosx
let sdk.dir point to your ANDROID_HOME environment

**Comment by beansoftapp** [comment]
Since i've not tested  the plugin under Linux, so I'll do a research on what happened.

**Comment by alanpduque** [comment]
Thanks for the quick reply, 
The local.properties file worked for the sdk, but now it can't find the adb, probably the same problem happens with the $PATH environment variable, where the adb path is defined.
FYI, I tried creating a run configuration(with another intellij plugin) executing a sh file with the "run-android" command and the same problem happened.

**Comment by spitoglou** [comment]
@alanpduque Hi, I had the same issue and I found a solution by creating a link of the adb executable in a directory that the OS has access by default. In my case (Ubuntu 16.04), I did:
`sudo ln -s /Android/Sdk/platform-tools/adb  /bin/adb`
After this, the plugin finds adb without any problem.

Hope that helps...

**Comment by beansoftapp** [comment]
I've do a test on an centos desktop, however the virtualbox linux is a bit outdated and i can't setup a full node.js env on it.
Here is my ~/.bash_profile content:
-----
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

export JAVA_HOME=/soft/WebStorm-172.4343.25/jre
PATH=$PATH:$HOME/bin:$JAVA_HOME/bin

export PATH
-----
then I brings up a modified plugin on webstorm, and it reads path env correctly. Also i've copyed a java executable and rename it to adb, and webstorm finds it well.

And how webstorm or idea read the system env variable? it's a bit fun: it calls python -i $WEB_STORM_HOME/bin/printenv.py then got the output there.

So if anyone could help me with:
1. edit your ~/.bash_profile file like this to add adb to PATH env:
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home
export ANDROID_HOME=/Users/beansoft/Documents/Java/android-sdk-macosx
export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

2. check whether you can execute python in your terminal.

And send me the final result here.

And still i'm trying to setup an complete Linux env to do a real test.

![virtualbox_oracle linux_20_11_2017_14_04_12](https://user-images.githubusercontent.com/11939450/33004759-874a4dae-cdfd-11e7-8aaf-d44e6f992d61.png)

**Comment by beansoftapp** [comment]
I've found the reason, by default, most people config envs following the office react native guild will edit your bashrc like this:

PATH="~/Android/Sdk/tools:~/Android/Sdk/platform-tools:${PATH}"
export PATH

that's why adb can't be found, since IDEA plugin system doesn't parse ~/ as absolute path at all, so it can't found the adb command. To resolve this problem, it's really simple, replace ~ with an absolute path in your bashrc or bash_profile file, like this:

PATH="/home/your_username/Android/Sdk/tools:/home/your_username/Android/Sdk/platform-tools:${PATH}"
export PATH

**Comment by beansoftapp** [comment]
And seems @spitoglou 's solution is the most simple one step:

sudo ln -s ~/Android/Sdk/platform-tools/adb /usr/bin/adb

IDEA's bug can't be fixed by me, so i'd like to let u do a test and close this bug.

**Comment by alanpduque** [comment]
I tried openning intellij trough console and it really worked fine.
Since I don't want to do that every time, I will use @spitoglou approach to the problem, which worked perfectly too.
Thank you all very much for the help!

**Comment by asozcan** [comment]
`echo "export PATH=\$PATH:/Users/${USER}/Library/Android/sdk/platform-tools/" >> ~/.bash_profile`
above works too but you need to do a restart for linux/macos
