### ISSUE TITLE
Idea: New buttons

### ISSUE THREAD

**Issue by skay1994** [beansoftapp/react-native-console#19]
Add two more buttons for command ```gradlew clean``` and ```react-native uninstall ```

**Comment by beansoftapp** [comment]
https://github.com/beansoftapp/react-native-console/releases/tag/v1.1.1 
supported your commands and with some new functions:

Refactor UI buttons 
Add react-native uninstall 
Add react-native start 
Add gradlew clean 
Add react-native react-native-git-upgrade 
Add react-devtools 
Support yarn add project, dev, global dependencies 
Support npm add project, dev, global dependencies

**Comment by beansoftapp** [comment]
please give some star or invite your friends to use this plugin
