### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by lzctbyong** [beansoftapp/react-native-console#2]
one click always open a  new  terminal 
i think,  it's needless,
on the contrary,it makes me crazy when terminal is too much

**Comment by beansoftapp** [comment]
Good suggestion, in fact I've noticed this issue, some prototypes have made, but need some time to finish this feature, the finally effect will looks like the IDE's run window.

**Comment by lzctbyong** [comment]
when do you plan to update ?

**Comment by Muyangmin** [comment]
**Same issue and suggestion~
Waiting for plugin next update.**

**Comment by beansoftapp** [comment]
Dears, I'm now on a new corp and app stack is now stick on React Native, yet I need some time to learn both RN, and I'd like to finish this feature in two weeks.

Thanks for your await!

**Comment by beansoftapp** [comment]
BTW, my wechat: weblogic , welcome to talk about RN and this plugin!

**Comment by lzctbyong** [comment]
Great~It's useful for us

**Comment by beansoftapp** [comment]
Hello guys, thanks for your waiting, here is the new version:
https://github.com/beansoftapp/react-native-console/blob/1.0.4/screenshot/ReactNativeConsole.png

You can also update it manually:
https://github.com/beansoftapp/react-native-console/blob/1.0.4/react-native-console.jar

also this will be upload to IDEA plugin central.

**Comment by beansoftapp** [comment]
new bugs found... awating

**Comment by beansoftapp** [comment]
Hello, bugs fixed, https://github.com/beansoftapp/react-native-console/blob/1.0.5/react-native-console.jar , please update manually and I'll update the plugin repository.

Critical bug fix: Windows command run fail with npm, react-native and gradlew.

Thanks for your feedback!
