### ISSUE TITLE
不能进入单个model、

### ISSUE THREAD

**Issue by fanshuzaizai** [beansoftapp/react-native-console#22]
目前所有命令只能在projext根目录下操作，而我得rn项目只是里面得一个model，导致所有得操作都无效，建议增加一个控制台或者选择目录功能

**Comment by beansoftapp** [comment]
给个目录结构图看看

**Comment by beansoftapp** [comment]
指定JS项目工作目录, 例如 ./jsapp (可选, 必须在.idea目录创建文件 .rnconsole , 内容和下面类似:

{
  currentPath: './jsapp'
}
之后所有的 npm 命令都会用这个目录作为启动目录
不知道这个能不能满足
