### ISSUE TITLE
Unable to run the commandline:Cannot run program "react-native" (in directory "xxx"): error=2, No such file or directory

### ISSUE THREAD

**Issue by clzd0792** [beansoftapp/react-native-console#23]
系统是 macOS High Sierra，AS 和 Idea 使用插件都报这个错（包括adb、npm、yarn等都报错）。
本来一切都 ok 的，初步怀疑是 chsh 切换 shell 为 zsh 后出现问题，但是切换回 bash 后问题依旧。
手动使用系统的终端输入命令都是可以正常使用的。请大佬帮忙看看是什么问题。

**Comment by clzd0792** [comment]
😂，刚才试了下又恢复正常了。昨天是有重启试过的。不知是什么原因。

**Comment by beansoftapp** [comment]
取命令实际路径的实现依赖的是IDEA的库, 它们有个python脚本读取系统变量然后再去找可执行文件位置, 可能IDEA这块偶尔不稳定.

**Comment by crobinson42** [comment]
Restarting Webstorm usually solves this issue - I find it's typically related to running Android Studio at the same time and the `adb` server not matching so a new server is started and this causes the issues to appear in Webstorm.
