### ISSUE TITLE
Cannot find entry file index.android.js in any of the roots:

### ISSUE THREAD

**Issue by TanWenPing** [beansoftapp/react-native-console#24]
C:\Users\android-02\AppData\Roaming\npm\react-native.cmd bundle --platform android --entry-file index.android.js --reset-cache --bundle-output android/app/src/main/assets/index.android.bundle --dev false --assets-dest android/app/src/main/res/
Scanning folders for symlinks in E:\work\workspace\TotoLink_JiWeng_ReactNative\TotoLink_JiWeng\node_modules (66ms)
Scanning folders for symlinks in E:\work\workspace\TotoLink_JiWeng_ReactNative\TotoLink_JiWeng\node_modules (150ms)
Loading dependency graph, done.

Cannot find entry file index.android.js in any of the roots: ["E:\\work\\workspace\\TotoLink_JiWeng_ReactNative\\TotoLink_JiWeng"]

Process finished with exit code 1

**Comment by TanWenPing** [comment]
C:\Users\android-02\AppData\Roaming\npm\react-native.cmd bundle --platform android --entry-file index.android.js --reset-cache --bundle-output android/app/src/main/assets/index.android.bundle --dev false --assets-dest android/app/src/main/res/
Scanning folders for symlinks in E:\work\workspace\TotoLink_JiWeng_ReactNative\TotoLink_JiWeng\node_modules (66ms)
Scanning folders for symlinks in E:\work\workspace\TotoLink_JiWeng_ReactNative\TotoLink_JiWeng\node_modules (150ms)
Loading dependency graph, done.

Cannot find entry file index.android.js in any of the roots: ["E:\work\workspace\TotoLink_JiWeng_ReactNative\TotoLink_JiWeng"]

Process finished with exit code 1

**Comment by beansoftapp** [comment]
E:\work\workspace\TotoLink_JiWeng_ReactNative\TotoLink_JiWeng
这是脚本执行时的根目录, 应该有个文件
E:\work\workspace\TotoLink_JiWeng_ReactNative\TotoLink_JiWeng\index.android.js
能否列一下目录结构

**Comment by liloveopen** [comment]
因为使用的是新版的react-native，再其根目录下是没有index.android.js这个js文件的。需要通过这个命令来实现：React-native bundle --entry-file index.js --bundle-output ./android/app/src/main/assets/index.android.bundle --platform android --assets-dest ./android/app/src/main/res/

**Comment by beansoftapp** [comment]
已修复, 请第一时间试用: https://github.com/beansoftapp/react-native-console/blob/1.1.5/react-native-console.jar 手工下载安装. 官方仓库正在更新中.
