### ISSUE TITLE
Update to 1.1.7 failed to reopen the Intellij IDEA

### ISSUE THREAD

**Issue by sure2win** [beansoftapp/react-native-console#26]
IntelliJ IDEA 2016.3.7
JRE: 1.8.0_112-release-408-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Earlier plugin version was fine, updated to the latest 1.1.7 and its failing to launch the IDE.
<img width="471" alt="screen shot 2018-08-02 at 2 23 51 am" src="https://user-images.githubusercontent.com/26094533/43548294-2fa215f2-95fb-11e8-9a36-5546d19b91f1.png">

**Comment by beansoftapp** [comment]
I'll take a look at.

**Comment by sure2win** [comment]
Perfect! That was quick and appreciate your efforts. No issues in opening IDE with the provided jar. thanks.
