### ISSUE TITLE
[Proposal] run-android with options.

### ISSUE THREAD

**Issue by sekitaka** [beansoftapp/react-native-console#29]
Thank you for the grate plugin! I love it!!

But I have a proposal.
I usually `react-native run-android` with the option `--appIdSuffix dev`.
So I propose to add run-android option settings.

Thanks.

**Comment by beansoftapp** [comment]
This issue has been fixed, please download https://github.com/beansoftapp/react-native-console/blob/master/react-native-console.jar to test it. And i've submit a plugin update.

![image](https://user-images.githubusercontent.com/11939450/63422042-3521cc00-c43c-11e9-82ae-fe78f566912c.png)

**Comment by sekitaka** [comment]
@beansoftapp Thank you sooooooooo much 🎉 
I've checked the feature. It works as I want.
