### ISSUE TITLE
React Native Console: Unable to run the commandline

### ISSUE THREAD

**Issue by zengqingsong** [beansoftapp/react-native-console#3]
上一个版本还可以用，更新之后就出现如下错误。Windows 8系统。
React Native Console: Unable to run the commandline:Cannot run program "C:\Program" (in directory "D:\react-native\DelliEdu"): CreateProcess error=193, %1 不是有效的 Win32 应用程序

**Comment by sionsxie** [comment]
Windows10系统  Version:1.0.4
Unable to run the commandline:Cannot run program "C:\Users\Love_xie\AppData\Roaming\npm\react-native" (in directory "D:\ReactNativeTest"): CreateProcess error=193, %1 不是有效的 Win32 应用程序

**Comment by beansoftapp** [comment]
已修复, 请第一时间试用: https://github.com/beansoftapp/react-native-console/blob/1.0.4/react-native-console.jar 手工下载安装. 官方仓库正在更新中.

**Comment by beansoftapp** [comment]
如果试了还不行, 请尽快反馈. 因为我现在暂时手头没有Windows机器. 另外欢迎加微信weblogic及时沟通bug情况.

**Comment by beansoftapp** [comment]
Hello, bugs fixed, https://github.com/beansoftapp/react-native-console/blob/1.0.5/react-native-console.jar , please update manually and I'll update the plugin repository.

Critical bug fix: windows command run fail with npm, react-native and gradlew.

Thanks for your feedback!
