### ISSUE TITLE
script description with whitespace didn't work

### ISSUE THREAD

**Issue by xstable** [beansoftapp/react-native-console#31]
If you have a script description like this, it doesn't work if you click it inside react-native-console:
```
"scripts": {
        "LINUX_install APK to USB": "adb -s `adb -d get-serialno` install -r `find -name app-release.apk`",
    },
```

![image](https://user-images.githubusercontent.com/1778068/51706869-09627300-2020-11e9-8414-c13f5ce4a0b8.png)

On "npm script-runner" it works like a charm. 
Please fix this.

**Comment by beansoftapp** [comment]
Please download https://github.com/beansoftapp/react-native-console/blob/master/react-native-console.jar to test it.
