### ISSUE TITLE
 Can not run program" adb ": error = 2, No such file or directory"

### ISSUE THREAD

**Issue by kyungjoongo** [beansoftapp/react-native-console#32]
When I press the android reload js button, the following message appears.

"Unable to run the commandline: Can not run program" adb ": error = 2, No such file or directory"
Let me know how to fix it!

**Comment by beansoftapp** [comment]
you must add this adb command to your PATH variable.

**Comment by kyungjoongo** [comment]
"brew cask reinstall android-platform-tools"
Resolved by command.
Thanks for the answer. ~

**Comment by kyungjoongo** [comment]
It is a very useful and good plugin.
I can not develop react-native app without this.

**Comment by beansoftapp** [comment]
thx so much, this plugin is first for my personal daily react-native dev, then i decided to share to peoples like me.
