### ISSUE TITLE
phpstrom 2019.1.3的版本已经无法搜索到查件了

### ISSUE THREAD

**Issue by pausermake** [beansoftapp/react-native-console#33]
phpstrom 2019.1.3的版本已经无法搜索到查件了

**Comment by beansoftapp** [comment]
我也发现了 IDEA 2019 也没法搜到, 旧版可以, 别人的老插件一直没更新的还能搜到, 我有时间试试提个新版本

**Comment by beansoftapp** [comment]
原因已经找到, 新版已提交, 预计在2个工作日内插件中心会通过审核.
