### ISSUE TITLE
reload js 不能正常使用

### ISSUE THREAD

**Issue by laibao101** [beansoftapp/react-native-console#34]
## 硬件
系统：mac os 10.14.5
手机：小米8
手机系统版本：miui 10.3.4
ide: webstrom 2019.1.4

## 问题
使用cmd+f2 的reload js功能，不能正常reload。只是把应用切到多任务界面。 使用与不使用全面屏都是这种效果。
![qq_pic_merged_1564973478283](https://user-images.githubusercontent.com/17879221/62435504-fd91ff00-b76e-11e9-8680-f12baa426281.jpg)

ide的界面为
![image](https://user-images.githubusercontent.com/17879221/62435388-8d837900-b76e-11e9-9dc3-97ca4a1d3403.png)

## 我希望什么

我希望能正常reload

**Comment by beansoftapp** [comment]
这个功能不是官方的, 而是一项模拟键盘事件: 菜单 空格 回车 回车 你发下RN版本 我看下

**Comment by laibao101** [comment]
"react": "^16.8.3",
"react-native": "^0.59.9",

**Comment by beansoftapp** [comment]
This issue has been fixed, please download https://github.com/beansoftapp/react-native-console/blob/master/react-native-console.jar to test it. And i've submit a plugin update.
