### ISSUE TITLE
When press reload button app start remote js debugging

### ISSUE THREAD

**Issue by fouad1994** [beansoftapp/react-native-console#35]
When I press reload button my app start remote JS debugging like if I press it manually what is the solution?

**Comment by beansoftapp** [comment]
This function is just a simulation of press: menu key, down key and enter key, and it's not a official function provided by react native cli. And i need your RN version to reproduce.

**Comment by beansoftapp** [comment]
This issue has been fixed, please download https://github.com/beansoftapp/react-native-console/blob/master/react-native-console.jar to test it. And i've submit a plugin update.
