### ISSUE TITLE
Bug: CreateProcess error=193, %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by saravanabalagi** [beansoftapp/react-native-console#36]
React Native Console: Unable to run the commandline:Cannot run program "C:\Users\username\AppData\Roaming\npm\react-native" (in directory "F:\Projects\js\myApp"): CreateProcess error=193, %1 is not a valid Win32 application

![image](https://user-images.githubusercontent.com/8567893/66698808-0fe16980-ecd9-11e9-8322-25e76a27721f.png)

I'm on Windows 10
IDEA Ultimate 2019.2.3

**Comment by beansoftapp** [comment]
would u like to send me the react native version and installation script

**Comment by saravanabalagi** [comment]
Hi @beansoftapp, thanks for your reply. I'm using React Native 0.59.4

`Debug Android` button works, but `Android Choose Devices` fails. What do you mean by installation script? I installed it from the Jetbrains Plugins directly

**Comment by beansoftapp** [comment]
Thanks for your report, this issue reproduced on my Win10 laptop, as I rarelly using it for coding. I'll fix it soon.

**Comment by beansoftapp** [comment]
https://github.com/beansoftapp/react-native-console/blob/2019.2/react-native-console.jar pls have a try. Plugin update will be available at IDEA plugin center soon.
