### ISSUE TITLE
[Linux]  Run npm scripts with requesting user input

### ISSUE THREAD

**Issue by Darkilen** [beansoftapp/react-native-console#37]
Hello,

I have a script bash who wait for the user to select one option between many.

When I run the script with my local terminal, the jetbrain built-in terminal or npm built-in feature, it works fine. But when I run this script with `run npm scripts` from RN Console, I can't enter text, it's look like a read-only terminal.

How can I do to make it works ?
Thanks

**Comment by beansoftapp** [comment]
This could be done, but need the IDEA 2019.2 x version with the latest terminal support. I'll do a research on it soon.

**Comment by beansoftapp** [comment]
This issue has been fixed, please download https://github.com/beansoftapp/react-native-console/blob/master/react-native-console.jar to test it. And i've submit a plugin update.

And this fix works on WebStorm 2017 to 2019. Pls have a try.

**Comment by Darkilen** [comment]
It works fine with this jar, thanks.
