### ISSUE TITLE
Add "./gradlew bundleRelease" to Icons-Toolbar

### ISSUE THREAD

**Issue by xstable** [beansoftapp/react-native-console#38]
You only have `assembleRelease` in the Icon-Bar to create an APK.
Please change it to... (or add) `./gradlew bundleRelease` to create a bundle for Android.

**Comment by beansoftapp** [comment]
This issue has been fixed, please download https://github.com/beansoftapp/react-native-console/blob/master/react-native-console.jar to test it. And i've submit a plugin update.
