### ISSUE TITLE
List Android emulator

### ISSUE THREAD

**Issue by thienlhh** [beansoftapp/react-native-console#40]
I have a question that can the plugin support list Android emulators like iOS. Which show the emulators then launch them when clicking on.

<img width="494" alt="Screen Shot 2019-12-14 at 11 46 57 AM" src="https://user-images.githubusercontent.com/5525866/70843595-7e70ae00-1e67-11ea-9e66-0da199444122.png">

**Comment by beansoftapp** [comment]
I need to do a investigate, not sure.

**Comment by mym0404** [comment]
How can i launch app using specific iOS device? when I select one in above iOS device list, noting happen..

**Comment by beansoftapp** [comment]
@mym0404 This function now only works on RN 0.60+(As I tried), it's a bug that old RN versions dosen't work on latest XCode, ant it's facebook's fault.

You can check your RN version.

**Comment by beansoftapp** [comment]
@thienlhh The avd list function is done, try this plugin jar first:
https://github.com/beansoftapp/react-native-console/blob/2019.2/react-native-console.jar
