### ISSUE TITLE
React Packager Error 

### ISSUE THREAD

**Issue by lzctbyong** [beansoftapp/react-native-console#6]
Unable to run the commandline:Cannot run program "D:\nodejs\npm" (in directory "D:\Project\wxsh"): CreateProcess error=193, %1 不是有效的 Win32 应用程序。

**Comment by beansoftapp** [comment]
Hello, bugs fixed, https://github.com/beansoftapp/react-native-console/blob/1.0.5/react-native-console.jar , please update manually and I'll update the plugin repository.

Critical bug fix: windows command run fail with npm, react-native and gradlew.

Thanks for your feedback!

**Comment by lzctbyong** [comment]
ok
