### ISSUE TITLE
Release APK  Error

### ISSUE THREAD

**Issue by lzctbyong** [beansoftapp/react-native-console#8]
Unable to run the commandline:Cannot run program ".\gradlew.cmd" (in directory "D:\Project\wxsh\android"): CreateProcess error=2, 系统找不到指定的文件。

**Comment by beansoftapp** [comment]
Confirmed, since there only a gradlew.bat file, no gradlew.cmd file.

**Comment by beansoftapp** [comment]
https://github.com/beansoftapp/react-native-console/blob/master/react-native-console.jar you can try this, i've tested all buttons function under windows.

**Comment by lzctbyong** [comment]
@beansoftapp It works well now with your new jar
