### ISSUE TITLE
Add new command for watchman to re-watch the project dir

### ISSUE THREAD

**Issue by sytolk** [beansoftapp/react-native-console#9]
command line:

`watchman watch-del /home/user/project_dir ; watchman watch-project /home/user/project_dir`

**Comment by beansoftapp** [comment]
I'll add this in next release.

**Comment by beansoftapp** [comment]
still working on, be cause idea's exec function can't run this command, it treats it like one command with wrong args.

**Comment by sytolk** [comment]
I think you can separate it in two commands 
exec('watchman watch-del /home/user/project_dir');
exec('watchman watch-project /home/user/project_dir');

**Comment by beansoftapp** [comment]
@sytolk I've using a more generic way: 
1. add scripts to your package.json:

`"scripts": {
    "test": "jest",
    "rewatchman" : "watchman watch-del .;watchman watch-project ."
  }`

2. click the npm dropdown toolbar button of RN Console to run it directly.

I've tested that and it works.

https://github.com/beansoftapp/react-native-console/blob/master/react-native-console.jar, you can download it now for a test, and 1.0.9 will be public at IDEA plugin center soon.

**Comment by sytolk** [comment]
It works. Thanks!
